### ISSUE TITLE
Clone failed

### ISSUE THREAD

**Issue by fathur** [mnir/ditemukan#1]
Ini kenapa ya gan? kok ane error cloningnya
![cloneerror](https://cloud.githubusercontent.com/assets/846678/2688744/0abecfdc-c2c4-11e3-8950-e33e5d41eb46.png)

**Comment by mnir** [comment]
Hasil dari git status apa tuh gan?

**Comment by fathur** [comment]
Panjang banget git statusnya:

Bagian atas:
![gitstatus1](https://cloud.githubusercontent.com/assets/846678/2688832/b4aa5e70-c2cf-11e3-9df5-bf2ba751e6a4.png)

Bagian tengah:
![gitstatus2](https://cloud.githubusercontent.com/assets/846678/2688852/4fc5ea5a-c2d0-11e3-83ad-9b146dc94a7c.png)

Bagian akhir:
![gitstatus3](https://cloud.githubusercontent.com/assets/846678/2688835/17867ede-c2d0-11e3-9486-51fc3ccb2299.png)

**Comment by mnir** [comment]
wah kok deleted ya?

**Comment by fathur** [comment]
mungkin keterbatasan filesystem Wind**s. 
Ane coba di Linux, cloning suxez.... :smile: 

Walaupun ane masih penasaran di Windo**s :triumph:

**Comment by mnir** [comment]
ane ada update untuk start.php + enviroment.php ga sengaja ke ignore kemaren... di git status lagi coba gan...
Jadi agan tinggal bikin 1 folder + 1 file:
app/config/local/database.php <-- isinya copy dari app/config/database.php dan ubah setingan databasenya yag di app/config/local/database.php

**Comment by fathur** [comment]
Not worked gan...
Ane cari2 dapet ini...

http://www.briantist.com/errors/failed-to-clone-the-repository-github-for-windows/

**Comment by gusdecool** [comment]
@fathur Wah, kalau udah bugs dari githubnya. kita ngga bisa apa gan. Tadi kalau gw clone di mac lancar jaya sih. Cuma shell `artisan` aja yang belum mau jalan

**Comment by fathur** [comment]
Ok ane agak tricky,,, clone di linux berhasil...
terus kodenya move ke Wind**s, soalnya ane kerja di Wind**s :sob: 

Thanks semuanya...
