### ISSUE TITLE
Where is database sql file?

### ISSUE THREAD

**Issue by fathur** [mnir/ditemukan#2]
Maaf gan kalo banyak tanya, mumpung ada media belajarnya. :smile: 
File database.sql nya dimana ya?

**Comment by mnir** [comment]
Edit:
untuk database.sql memang tidak ada. Soalnya saya sudah buatkan file database migration + seed nya.

**Comment by fathur** [comment]
## **Solved**

Stepnya:
- Setting app/config/database.php untuk terkoneksi dengan database server Anda
- Ketikkan: `php artisan migrate`
- Kemudian: `php artisan db:seed`
